### PR TITLE
Magento Patch SUPEE-6285 Fix

### PR DESCRIPTION
**Pull request by buric**

### CODE REVIEW

**Comment by colinodell** [comment]
+1

**Comment by GraafG** [comment]
Do i have to set an extra role for a user?
After the SUPEE patch i get "Access denied" on LoginAsCustomer for a limited user with Managa user roles.

**Comment by calicocook** [comment]
We had to patch our contribution and add an ACL, we are EE 1.12.  The version of the module we have, had no roles implemented we could find, a common patch is to just implement the following as "return true;" but then that allows all users with admin logins to access it.

app/code/community/Inchoo/LoginAsCustomer/controllers/Adminhtml/Inchoo/LoginAsCustomerController.php
-    /**
-     \* Post SUPEE-6285 all custom modules intended
-     \*    for users who have selective permissions (not admin permissions) need to implement this.
-     *
-     \* @return bool
-     */
-    protected function _isAllowed()
-    {
-        return Mage::getSingleton('admin/session')->isAllowed('system/config/inchoo_loginAsCustomer');
-    }

app/code/community/Inchoo/LoginAsCustomer/etc/config.xml

```
<acl>
    <resources>
        <admin>
            <children>
                <system>
                    <children>
                        <config>
                            <children>
                                <inchoo_loginAsCustomer>
                                    <title>Inchoo Login As Customer</title>
                                </inchoo_loginAsCustomer>
                            </children>
                        </config>
                    </children>
                </system>
            </children>
        </admin>
    </resources>
</acl>
```

**Comment by peterjaap** [comment]
@ajzele also this one? Also verified as working.

**Pull request closed without merging**
